### ISSUE TITLE
Icons get blurred under Gnome Shell.

### ISSUE THREAD

**Issue by saq1610** [Pinbadge/pinbadge-linux-theme#17]
![pinbadge_bad_icons](https://cloud.githubusercontent.com/assets/10332349/10452510/e18afe5a-71be-11e5-9abd-7c031cd9a102.png)

It seems that the icons dont scale properly but this can't be since all the icons are SVG's. Weird.
@crutchcorn

**Comment by loctauxphilippe** [comment]
does that as well with materialos
github.com/materialos/Linux-Icon-Pack

**Comment by saq1610** [comment]
![screenshot from 2015-10-13 14-41-24](https://cloud.githubusercontent.com/assets/10332349/10461537/34442f52-71f3-11e5-9ee8-0a985b620edf.png)
Icons also look weird here. Some huge and blurred while some small and OK.
@crutchcorn

**Comment by crutchcorn** [comment]
Notice how all the symbolic links are that way and the actual icons aren't @saq1610 . This must be a Nautilus bug. 

To fix the blur issue, we have to create folder for /apps/16,22,24,32,48,64,128 instead of just 48. I will do this soon enough. But dang will that take FOREVER on me

**Comment by adueppen** [comment]
Was just looking at the icons, and for some reason, a few here and there are 192x192px instead of 48x48px. That may be of relevance.

**Comment by crutchcorn** [comment]
Aye dios mio... I HATE AI with it's BS with SVGs.... I need to go back and redo ALL the SVGs one of these days...

**Comment by adueppen** [comment]
You might want to use Inkscape for the SVGs since you can make sure that they're W3 compliant.

**Comment by crutchcorn** [comment]
I don't know inkscape, nor do I have the time to learn it. :(

**Comment by crutchcorn** [comment]
We will be moving to PNGs over SVGs starting tonight. @borth92 has given me some new info which helps me be able to move to PNG. Thanks @borth92!!!

**Comment by crutchcorn** [comment]
Fixed in d695c0e5dbe68c4fbfd6d0e74078bb521812a677
